language: node_js
node_js:
  - "5.0.0"
install:
  - npm install phantomjs -g
  - npm install -g mocha-phantomjs
  - npm install
before_script:
  - phantomjs --version
  - mocha-phantomjs --version
script:
  - npm bin
  - npm run build-js
  - npm run test-mocha
