language: node_js
node_js:
  - "12.14.1"
sudo: false
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
cache:
  yarn: true
install:
  - yarn
script:
  #- yarn bin
  #- yarn build-js
  - yarn test
